name: Changelogger
author: Colt Alan Bauman
description: >
  Outputs a changelog diff since the last full release. I'm a fan of standard-version,
  but at the time of writing it doesn't support including prerelease commits when a
  full release is made. This addresses that limitation.

inputs:
  preamble:
    description: >
      Message positioned before the list of commits. Prefixed with '## ' (header markdown).
    default: What's changed?
    required: false
  is-conventional:
    description: >
      If false, it just returns a simple list of commits messages.
      If true, it parses conventional commits and organizes them into sections
      (like any conventional changelog library).
      By default, only feat, fix, and breaking changes are included.
      Will use the .versionrc file if present in the root directory.
    required: false
    default: 'true'
  output-flavor:
    description: >
      Options: github-release, markdown, slack
      github-release: GitHub Releases support autolinked references + formatting.
        Source: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls
      markdown: Basic GitHub markdown without autolinked references. This option
      isn't ready yet so it currenlty uses github-release as a fallback.
      slack: Slack uses its own special markup language called mrkdwn.
        Source: https://api.slack.com/reference/surfaces/formatting
    required: false
    default: github-release
  branch-comparison-strategy:
    description: >
      Options: tag, workflow
      Only applies when the workflow trigger ref starts with `refs/heads/`
      tag: searches for the last non-prerelease tag, and uses that to compare against HEAD
      workflow: searches for the last successful workflow run for the current branch + current workflow,
        and uses that to compare against HEAD
    required: false
    default: tag
  token:
    description: Used to access releases and workflows.
    default: ${{ github.token }}
    required: false

  # Consider adding postamble like: Full Changelog: v11.2.3...v11.3.0
  # Consider adding option to include author(s): @cabauman
  # Consider adding option to customize format: {{sha}} {{commit-message}} {{author}}
  # Consider adding option to filter out certain commits. Either regex or js predicate function.
  # Consider adding option to specify .versionrc path.

outputs:
  changelog:
    description: The generated changelog for the new version.

runs:
  using: node20
  main: dist/index.js
