name: 'Changelogger'
author: 'Colt Alan Bauman'
description: 'Outputs a changelog diff'
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
    required: false
  # Consider getting rid of this option.
  max-commits:
    description: 'Max number of commits to include in the output'
    required: false
    default: '100'
  # Consider adding postamble like: Full Changelog: v11.2.3...v11.3.0
  preamble:
    description: >
      Message positioned before the list of commits. This message is displayed
      even if the retrieval of commits fails.
    required: false
  # Consider only supporting conventional commits.
  is-conventional:
    description: >
      Parse conventional commits and organize into sections (like conventional changelog libraries).
      By default, only feat, fix, and breaking changes are included.
      Will use the .versionrc file if present.
    required: false
    default: 'true'
  markdown-flavor:
    description: >
      Either slack or github
    required: false
    default: 'github'
  # Consider only supporting tag comparisons.
  branch-comparison-strategy:
    description: >
      Either tag or workflow
      Only applies when the workflow trigger ref starts with `refs/heads/`
      tag: searches for the last non-prerelease tag, and uses that to compare against HEAD
      workflow: searches for the last successful workflow run for the current branch + current workflow,
        and uses that to compare against HEAD
    required: false
    default: 'tag'
  # Consider adding formatting support: {{sha}} {{commit-message}}

runs:
  using: 'node16'
  main: 'dist/index.js'
