name: CI

on:
  workflow_dispatch:
    inputs:
      output-flavor:
        type: choice
        required: true
        description: Which kind of markdown to use
        default: markdown
        options: 
          - markdown
          - github-release
          - slack
  pull_request:
    branches: [ main ]

jobs:
  npm-install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm test

  # Make sure the action works on a clean machine without building.
  execute-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: run-action
        with:
          is-conventional: true
          output-flavor: ${{ github.event.inputs.output-flavor }}
          preamble: Test was successful
      - run: echo "The output is '${{ steps.run-action.outputs.changelog }}'"
