name: Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: Prerelease tag (optional)
        required: false
        type: string
        default: ''
      release-as:
        required: true
        type: choice
        default: auto
        description: If you want an automated or a manual version bump
        options:
          - auto
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Version bump
        env:
          PRERELEASE: ${{ github.event.inputs.prerelease }}
          RELEASE_AS: ${{ github.event.inputs.release-as }}
        run: >
          npx standard-version --skip.changelog 
          ${{ env.PRERELEASE != '' && format('--prerelease {0}', env.PRERELEASE) || '' }}
          ${{ env.RELEASE_AS != 'auto' && format('--release-as {0}', env.RELEASE_AS) || '' }}

      - name: Get latest tag
        id: get-latest-tag
        run: echo ::set-output name=version-tag::$(git describe --tags --abbrev=0)

      - name: Generate changelog
        id: changelog
        uses: ./
        with:
          is-conventional: true
          preamble: What's changed?

      - name: Get base version
        id: get-base-version
        env:
          VERSION_TAG: ${{ steps.get-latest-tag.outputs.version-tag }}
        run: |
          base_version=$(echo ${{ env.VERSION_TAG }} | cut -d- -f1)
          echo ::set-output name=base-version::$base_version

      - name: Commit changes
        env:
          VERSION_TAG: ${{ steps.get-latest-tag.outputs.version-tag }}
        run: |
          git push origin ${{ env.VERSION_TAG }}
          git push origin main

      - name: Upsert release
        uses: actions/github-script@v6.1.0
        env:
          BASE_VERSION: ${{ steps.get-base-version.outputs.base-version }}
          RELEASE_NAME: ${{ steps.get-latest-tag.outputs.version-tag }}
          PRERELEASE: ${{ github.event.inputs.prerelease != '' }}
          BODY: ${{ steps.changelog.outputs.commit-list }}
        with:
          script: |
            const { BASE_VERSION, RELEASE_NAME, PRERELEASE, BODY } = process.env
            const { owner, repo } = context.repo
            const { data } = await github.rest.repos.listReleases({ owner, repo, per_page: 1 })
            const release = data.length > 0 ? data[0] : undefined
            if (release && release.tag_name.startsWith(BASE_VERSION)) {
              await github.rest.repos.updateRelease({
                owner,
                repo,
                release_id: release.id,
                prerelease: PRERELEASE === 'true',
                name: RELEASE_NAME,
                tag_name: RELEASE_NAME,
                body: BODY,
              })
            } else {
              await github.rest.repos.createRelease({
                owner,
                repo,
                prerelease: PRERELEASE === 'true',
                name: RELEASE_NAME,
                tag_name: RELEASE_NAME,
                body: BODY,
              })
            }
